# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='unit',
            field=models.CharField(default='分钟', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='personnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='truepersonnum',
            field=models.IntegerField(default=0),
        ),
    ]
