# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorword',
            name='anchorid',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='anchorid',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='userid',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
