# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0004_auto_20190802_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='gametimeid',
            field=models.IntegerField(null=True),
        ),
    ]
