# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0005_auto_20190802_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameword',
            name='anchordefined',
            field=models.IntegerField(default=0),
        ),
    ]
