# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0006_auto_20190802_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='wordsmallcategoryid',
            field=models.IntegerField(null=True),
        ),
    ]
