# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0008_auto_20190803_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameword',
            name='gameid',
            field=models.IntegerField(),
        ),
    ]
