# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0009_auto_20190803_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='roomdid',
            field=models.CharField(default=900321, max_length=48),
        ),
    ]
