# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0011_auto_20190803_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=48)),
                ('pricture', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('useid', models.CharField(max_length=48)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'userrecord',
            },
        ),
    ]
