# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0013_auto_20190804_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='useid',
            field=models.CharField(max_length=128),
        ),
    ]
