# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0014_auto_20190804_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameword',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
