# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0017_auto_20190804_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='usertime',
            field=models.CharField(default=61, max_length=48),
        ),
    ]
