# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0018_auto_20190804_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameword',
            name='personnum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
