# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-04 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0019_auto_20190804_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'ordering': ['usertime']},
        ),
    ]
