# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0020_auto_20190804_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='usertime',
            field=models.IntegerField(default=61),
        ),
    ]
