# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-05 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0021_auto_20190805_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='truepersonnum',
            new_name='anchorscore',
        ),
    ]
