# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0028_auto_20190807_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='a1time',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='a2atime',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='a2btime',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='a3time',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='token',
            field=models.CharField(default=0, max_length=512),
        ),
        migrations.AddField(
            model_name='info',
            name='token',
            field=models.CharField(default=0, max_length=512),
        ),
    ]
