# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0029_auto_20190824_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='token',
            field=models.CharField(max_length=512),
        ),
    ]
