# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0031_gameword_a4time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='a1time',
            field=models.CharField(default=0, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='a2atime',
            field=models.CharField(default=0, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='a2btime',
            field=models.CharField(default=0, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='a3time',
            field=models.CharField(default=0, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='token',
            field=models.CharField(default=0, max_length=512, null=True),
        ),
    ]
